#!/usr/bin/env python3
"""PreToolUse hook — inject context from JSONL into subagent tasks.

Auto-generated by Harness. Customize for your project.

Triggered on: Task tool calls
Reads: {task_dir}/implement.jsonl, check.jsonl, debug.jsonl
Injects: File contents declared in JSONL into the agent's context
"""
import json
import os
import sys

HARNESS_DIR = os.path.join(os.getcwd(), ".harness")
MAX_FILES = 20
MAX_TOKENS_PER_FILE = 3000  # Approximate
MAX_CHARS_PER_FILE = MAX_TOKENS_PER_FILE * 4


def get_current_task_dir():
    """Read the current active task directory."""
    current_task_file = os.path.join(HARNESS_DIR, ".current-task")
    if not os.path.isfile(current_task_file):
        return None
    with open(current_task_file, "r") as f:
        return f.read().strip() or None


def detect_agent_type(tool_input):
    """Detect which pipeline stage this agent is for."""
    prompt = tool_input.get("prompt", "").lower()
    agent_type = tool_input.get("subagent_type", "").lower()

    if "check" in agent_type or "review" in agent_type:
        return "check"
    if "debug" in agent_type or "fix" in agent_type:
        return "debug"
    if "implement" in agent_type or "code" in agent_type:
        return "implement"
    if "finish" in agent_type:
        return "finish"

    # Fallback: scan prompt keywords
    if "check" in prompt or "review" in prompt or "verify" in prompt:
        return "check"
    if "debug" in prompt or "fix" in prompt:
        return "debug"
    if "implement" in prompt or "build" in prompt or "create" in prompt:
        return "implement"

    return "implement"  # Default


def read_jsonl(filepath):
    """Read a JSONL file, return list of entries."""
    entries = []
    if not os.path.isfile(filepath):
        return entries
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return entries


def resolve_file(file_path, task_dir):
    """Resolve file path relative to .harness/ or task dir."""
    # Try relative to .harness/
    candidate = os.path.join(HARNESS_DIR, file_path)
    if os.path.exists(candidate):
        return candidate

    # Try relative to task dir
    if task_dir:
        candidate = os.path.join(task_dir, file_path)
        if os.path.exists(candidate):
            return candidate

    # Try as absolute or project-relative
    if os.path.exists(file_path):
        return file_path

    return None  # File not found — silent skip (defensive design)


def read_file_content(filepath, max_chars=MAX_CHARS_PER_FILE):
    """Read file content with truncation."""
    try:
        with open(filepath, "r") as f:
            content = f.read(max_chars)
        if len(content) >= max_chars:
            content += "\n\n[... truncated — file exceeds token budget ...]"
        return content
    except (IOError, UnicodeDecodeError):
        return None


def read_directory_md_files(dirpath, max_chars=MAX_CHARS_PER_FILE):
    """Read all .md files in a directory."""
    contents = []
    if not os.path.isdir(dirpath):
        return None
    for fname in sorted(os.listdir(dirpath)):
        if fname.endswith(".md"):
            fpath = os.path.join(dirpath, fname)
            content = read_file_content(fpath, max_chars // 5)  # Budget per file
            if content:
                contents.append(f"### {fname}\n\n{content}")
    return "\n\n".join(contents) if contents else None


def main():
    if not os.path.isdir(HARNESS_DIR):
        return

    # Read hook input from stdin
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        return

    tool_name = hook_input.get("tool_name", "")
    if tool_name != "Task":
        return

    tool_input = hook_input.get("tool_input", {})
    task_dir = get_current_task_dir()
    if not task_dir:
        return

    agent_type = detect_agent_type(tool_input)

    # Determine which JSONL to read
    jsonl_path = os.path.join(task_dir, f"{agent_type}.jsonl")
    entries = read_jsonl(jsonl_path)

    # Also always include spec.jsonl as fallback
    if not entries:
        spec_jsonl = os.path.join(task_dir, "spec.jsonl")
        entries = read_jsonl(spec_jsonl)

    if not entries:
        return

    # Resolve and read files
    context_blocks = []
    files_loaded = 0

    for entry in entries[:MAX_FILES]:
        file_path = entry.get("file") or entry.get("path")
        if not file_path:
            continue

        file_type = entry.get("type", "file")
        resolved = resolve_file(file_path, task_dir)
        if not resolved:
            continue  # Silent skip — defensive design

        if file_type == "directory":
            content = read_directory_md_files(resolved)
        else:
            content = read_file_content(resolved)

        if content:
            reason = entry.get("reason", "")
            header = f"## [{file_path}]" + (f" — {reason}" if reason else "")
            context_blocks.append(f"{header}\n\n{content}")
            files_loaded += 1

    if context_blocks:
        result = (
            f"# Injected Context ({agent_type} stage, {files_loaded} files)\n\n"
            + "\n\n---\n\n".join(context_blocks)
        )
        json.dump({"result": result}, sys.stdout)


if __name__ == "__main__":
    main()
