#!/usr/bin/env python3
"""SubagentStop hook — quality gate enforcement.

Auto-generated by Harness. Customize for your project.

Triggered on: SubagentStop (when any subagent finishes)
Enforces:
- Verification commands must have been run
- Failure budget tracking (≤3 same-type failures)
- Agent output evidence collection
"""
import json
import os
import sys
from datetime import datetime

HARNESS_DIR = os.path.join(os.getcwd(), ".harness")
MAX_DEBUG_CYCLES = 3


def get_current_task_dir():
    """Read the current active task directory."""
    current_task_file = os.path.join(HARNESS_DIR, ".current-task")
    if not os.path.isfile(current_task_file):
        return None
    with open(current_task_file, "r") as f:
        return f.read().strip() or None


def load_task_state(task_dir):
    """Load task state from task-specific state file."""
    state_file = os.path.join(task_dir, ".state.json")
    if not os.path.isfile(state_file):
        return {"debug_count": 0, "failures": [], "passes": []}
    try:
        with open(state_file, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return {"debug_count": 0, "failures": [], "passes": []}


def save_task_state(task_dir, state):
    """Save task state atomically."""
    state_file = os.path.join(task_dir, ".state.json")
    tmp_file = state_file + ".tmp"
    with open(tmp_file, "w") as f:
        json.dump(state, f, indent=2)
    os.rename(tmp_file, state_file)


def detect_agent_type_from_output(output_text):
    """Detect which pipeline stage just completed."""
    output_lower = output_text.lower() if output_text else ""
    if "check" in output_lower or "review" in output_lower or "verify" in output_lower:
        return "check"
    if "debug" in output_lower or "fix" in output_lower:
        return "debug"
    if "implement" in output_lower:
        return "implement"
    return "unknown"


def check_verification_commands(output_text, task_dir):
    """Check if verification commands were mentioned in agent output."""
    # Read workflow.md for expected commands
    workflow_path = os.path.join(HARNESS_DIR, "workflow.md")
    expected_cmds = []
    if os.path.isfile(workflow_path):
        with open(workflow_path, "r") as f:
            for line in f:
                if line.strip().startswith("- **Test**:") or \
                   line.strip().startswith("- **Lint**:") or \
                   line.strip().startswith("- **Build**:"):
                    # Extract command between backticks
                    parts = line.split("`")
                    if len(parts) >= 2:
                        cmd = parts[1].strip()
                        if cmd and not cmd.startswith("_PLACEHOLDER"):
                            expected_cmds.append(cmd)

    if not expected_cmds:
        return True, []  # No commands configured, pass

    missing = []
    output_lower = (output_text or "").lower()
    for cmd in expected_cmds:
        if cmd.lower() not in output_lower:
            missing.append(cmd)

    return len(missing) == 0, missing


def main():
    if not os.path.isdir(HARNESS_DIR):
        return

    # Read hook input
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        return

    tool_output = hook_input.get("tool_output", "")
    task_dir = get_current_task_dir()
    if not task_dir:
        return

    state = load_task_state(task_dir)
    agent_type = detect_agent_type_from_output(tool_output)

    # Track debug cycles
    if agent_type == "debug":
        state["debug_count"] = state.get("debug_count", 0) + 1
        if state["debug_count"] >= MAX_DEBUG_CYCLES:
            warning = (
                f"\n\n## ⚠ Failure Budget Exhausted\n\n"
                f"Debug cycle {state['debug_count']}/{MAX_DEBUG_CYCLES} reached.\n"
                f"**STOP** and escalate to human.\n\n"
                f"Provide:\n"
                f"1. What was attempted (all {state['debug_count']} cycles)\n"
                f"2. What error persists\n"
                f"3. Your recommended approach\n"
                f"4. What information you're missing\n"
            )
            json.dump({"result": warning}, sys.stdout)
            save_task_state(task_dir, state)
            return

    # For check agents: verify that commands were actually run
    if agent_type == "check":
        passed, missing = check_verification_commands(tool_output, task_dir)
        if not passed and missing:
            reminder = (
                f"\n\n## Quality Gate: Missing Verification\n\n"
                f"The following commands were not detected in the output:\n"
            )
            for cmd in missing:
                reminder += f"- `{cmd}`\n"
            reminder += (
                f"\nPlease run these commands and verify they pass "
                f"before marking the task complete."
            )
            json.dump({"result": reminder}, sys.stdout)
            save_task_state(task_dir, state)
            return

    # Record completion timestamp
    state.setdefault("completions", []).append({
        "agent": agent_type,
        "timestamp": datetime.now().isoformat(),
    })

    save_task_state(task_dir, state)


if __name__ == "__main__":
    main()
