#!/usr/bin/env python3
"""SessionStart hook — inject global context at session start.

Auto-generated by Harness. Customize for your project.

Injected context:
- Workflow guide summary
- Top lessons from lessons/index.md
- Staleness warnings (if any)
"""
import json
import os
import sys

HARNESS_DIR = os.path.join(os.getcwd(), ".harness")


def main():
    if not os.path.isdir(HARNESS_DIR):
        return

    blocks = []

    # 1. Inject lessons index (always)
    lessons_index = os.path.join(HARNESS_DIR, "spec", "lessons", "index.md")
    if os.path.isfile(lessons_index):
        with open(lessons_index, "r") as f:
            content = f.read().strip()
        if content:
            blocks.append(f"## Project Lessons\n\n{content}")

    # 2. Inject staleness warnings (if any)
    stale_file = os.path.join(HARNESS_DIR, ".stale-knowledge.json")
    if os.path.isfile(stale_file):
        try:
            with open(stale_file, "r") as f:
                stale = json.load(f)
            if stale:
                warning_lines = ["## ⚠ Stale Knowledge Detected", ""]
                for entry in stale[:5]:  # Max 5 warnings
                    warning_lines.append(
                        f"- `{entry.get('file', '?')}` modified since "
                        f"`{entry.get('spec', '?')}` was last updated"
                    )
                blocks.append("\n".join(warning_lines))
        except (json.JSONDecodeError, KeyError):
            pass

    # 3. Inject current task context (if active)
    current_task_file = os.path.join(HARNESS_DIR, ".current-task")
    if os.path.isfile(current_task_file):
        with open(current_task_file, "r") as f:
            task_dir = f.read().strip()
        if task_dir:
            prd_path = os.path.join(task_dir, "prd.md")
            if os.path.isfile(prd_path):
                blocks.append(f"## Active Task\n\nSee: `{prd_path}`")

    if blocks:
        result = "\n\n---\n\n".join(blocks)
        # Output as JSON for hook protocol
        json.dump({"result": result}, sys.stdout)


if __name__ == "__main__":
    main()
