#!/usr/bin/env python3
"""PostToolUse hook — detect knowledge staleness.

Auto-generated by Harness. Customize for your project.

Triggered on: Edit, Write tool calls
Detects: When modified files overlap with JSONL-referenced files
Writes: .harness/.stale-knowledge.json
"""
import json
import os
import sys
from datetime import datetime

HARNESS_DIR = os.path.join(os.getcwd(), ".harness")
STALE_FILE = os.path.join(HARNESS_DIR, ".stale-knowledge.json")


def get_all_jsonl_references():
    """Collect all file references from all JSONL files in tasks/."""
    refs = set()
    tasks_dir = os.path.join(HARNESS_DIR, "tasks")
    if not os.path.isdir(tasks_dir):
        return refs

    for root, dirs, files in os.walk(tasks_dir):
        for fname in files:
            if fname.endswith(".jsonl"):
                fpath = os.path.join(root, fname)
                try:
                    with open(fpath, "r") as f:
                        for line in f:
                            line = line.strip()
                            if not line or line.startswith("#"):
                                continue
                            try:
                                entry = json.loads(line)
                                file_ref = entry.get("file") or entry.get("path")
                                if file_ref:
                                    refs.add(file_ref)
                            except json.JSONDecodeError:
                                continue
                except IOError:
                    continue

    # Also check spec files for references
    spec_dir = os.path.join(HARNESS_DIR, "spec")
    if os.path.isdir(spec_dir):
        for root, dirs, files in os.walk(spec_dir):
            for fname in files:
                if fname.endswith(".md"):
                    rel = os.path.relpath(os.path.join(root, fname), HARNESS_DIR)
                    refs.add(rel)

    return refs


def load_stale_entries():
    """Load existing stale knowledge entries."""
    if not os.path.isfile(STALE_FILE):
        return []
    try:
        with open(STALE_FILE, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return []


def save_stale_entries(entries):
    """Save stale knowledge entries atomically."""
    tmp_file = STALE_FILE + ".tmp"
    with open(tmp_file, "w") as f:
        json.dump(entries, f, indent=2)
    os.rename(tmp_file, STALE_FILE)


def main():
    if not os.path.isdir(HARNESS_DIR):
        return

    # Read hook input
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        return

    tool_name = hook_input.get("tool_name", "")
    if tool_name not in ("Edit", "Write", "MultiEdit"):
        return

    # Get modified file path
    tool_input = hook_input.get("tool_input", {})
    modified_file = tool_input.get("file_path", "")
    if not modified_file:
        return

    # Normalize to project-relative path
    project_root = os.getcwd()
    if modified_file.startswith(project_root):
        modified_file = os.path.relpath(modified_file, project_root)

    # Check if this file is referenced by any JSONL or spec
    refs = get_all_jsonl_references()

    # Check intersection
    is_referenced = False
    matching_spec = None
    for ref in refs:
        # Direct match or the modified file is inside a referenced directory
        if modified_file == ref or modified_file.startswith(ref + "/"):
            is_referenced = True
            matching_spec = ref
            break
        # The modified file's basename matches a reference
        if os.path.basename(modified_file) == os.path.basename(ref):
            is_referenced = True
            matching_spec = ref
            break

    if not is_referenced:
        return

    # Add stale entry
    entries = load_stale_entries()

    # Avoid duplicates
    existing_files = {e.get("file") for e in entries}
    if modified_file not in existing_files:
        entries.append({
            "file": modified_file,
            "spec": matching_spec,
            "detected": datetime.now().isoformat(),
        })
        save_stale_entries(entries)


if __name__ == "__main__":
    main()
